name: Deploy Maven Javadocs to GitHub Pages

on:
  release:
    types:
      - published

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Javadocs
        run: mvn clean javadoc:javadoc

      - name: Set version-based directory for Javadocs
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Using version: $VERSION"
          # Create a directory for the version
          mkdir -p target/reports/apidocs/$VERSION
          mv target/site/apidocs/* target/reports/apidocs/$VERSION/

      - name: Add CNAME file
        run: |
          echo "jd.slz.zetaplugins.com" > target/reports/apidocs/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/reports/apidocs